import type { IndexerDefinition } from './types'

// Public indexers that need no account and can be seeded automatically.
export const PUBLIC_INDEXER_CATALOG: IndexerDefinition[] = [
  {
    name: 'YTS',
    description: 'High-quality movie torrents. No account required.',
    search_type: 'yts',
    base_url: 'https://yts.gg',
    torznab_url: '',
    api_key: '',
    requires_auth: false,
    requires_flaresolverr: false,
    pending_credentials: null,
  },
  {
    name: 'EZTV',
    description: 'TV show releases. Requires IMDB ID for reliable search. No account required.',
    search_type: 'eztv',
    base_url: 'https://eztv.re',
    torznab_url: '',
    api_key: '',
    requires_auth: false,
    requires_flaresolverr: false,
    pending_credentials: null,
  },
  {
    name: 'Nyaa',
    description: 'Anime and Japanese media tracker. No account required.',
    search_type: 'nyaa',
    base_url: 'https://nyaa.si',
    torznab_url: '',
    api_key: '',
    requires_auth: false,
    requires_flaresolverr: false,
    pending_credentials: null,
  },
  {
    name: 'sukebei.nyaa.si',
    description: 'Adult-content sister site of Nyaa, same engine. No account required.',
    search_type: 'sukebei',
    base_url: 'https://sukebei.nyaa.si',
    torznab_url: '',
    api_key: '',
    requires_auth: false,
    requires_flaresolverr: false,
    pending_credentials: null,
  },
  {
    name: 'The Pirate Bay',
    description: 'General public tracker (movies, TV, and more). No account required.',
    search_type: 'thepiratebay',
    base_url: 'https://apibay.org',
    torznab_url: '',
    api_key: '',
    requires_auth: false,
    requires_flaresolverr: false,
    pending_credentials: null,
  },
  {
    name: 'Bangumi Moe',
    description: 'Anime and Japanese media tracker. No account required.',
    search_type: 'bangumimoe',
    base_url: 'https://bangumi.moe',
    torznab_url: '',
    api_key: '',
    requires_auth: false,
    requires_flaresolverr: false,
    pending_credentials: null,
  },
  {
    name: 'Internet Archive',
    description: 'Public-domain and freely-licensed media with a BitTorrent file. No account required.',
    search_type: 'internetarchive',
    base_url: 'https://archive.org',
    torznab_url: '',
    api_key: '',
    requires_auth: false,
    requires_flaresolverr: false,
    pending_credentials: null,
  },
  {
    name: 'nekoBT',
    description: 'Anime and general tracker with a standard Torznab feed. No account required.',
    search_type: 'torznab',
    base_url: 'https://nekobt.to',
    torznab_url: 'https://nekobt.to/api/torznab/api',
    api_key: '',
    requires_auth: false,
    requires_flaresolverr: false,
    pending_credentials: null,
  },
  {
    name: 'SubsPlease',
    description: 'Single-fansub-group anime tracker. No account required.',
    search_type: 'subsplease',
    base_url: 'https://subsplease.org',
    torznab_url: '',
    api_key: '',
    requires_auth: false,
    requires_flaresolverr: false,
    pending_credentials: null,
  },
  {
    name: 'TorrentsCSV',
    description: 'General-purpose public torrent search engine, unclassified results. No account required.',
    search_type: 'torrentscsv',
    base_url: 'https://torrents-csv.com',
    torznab_url: '',
    api_key: '',
    requires_auth: false,
    requires_flaresolverr: false,
    pending_credentials: null,
  },
  {
    name: 'LimeTorrents',
    description: 'General public tracker (movies, TV, and more). No account required.',
    search_type: 'limetorrents',
    base_url: 'https://www.limetorrents.fun',
    torznab_url: '',
    api_key: '',
    requires_auth: false,
    requires_flaresolverr: false,
    pending_credentials: null,
  },
  {
    name: 'BT.etree',
    description: 'Live-music (bootleg FLAC) tracker. .torrent-file downloads only, no magnets. No account required.',
    search_type: 'btetree',
    base_url: 'https://bt.etree.org',
    torznab_url: '',
    api_key: '',
    requires_auth: false,
    requires_flaresolverr: false,
    pending_credentials: null,
  },
  {
    name: 'Shana Project',
    description: 'Anime tracker. .torrent-file downloads only, no magnets. No account required.',
    search_type: 'shanaproject',
    base_url: 'https://www.shanaproject.com',
    torznab_url: '',
    api_key: '',
    requires_auth: false,
    requires_flaresolverr: false,
    pending_credentials: null,
  },
  {
    name: 'TorrentDownload',
    description: 'General torrent meta-search engine. No account required.',
    search_type: 'torrentdownload',
    base_url: 'https://www.torrentdownload.info',
    torznab_url: '',
    api_key: '',
    requires_auth: false,
    requires_flaresolverr: false,
    pending_credentials: null,
  },
  {
    name: 'Mikan',
    description: 'Chinese anime tracker. No account required.',
    search_type: 'mikan',
    base_url: 'https://mikanani.me',
    torznab_url: '',
    api_key: '',
    requires_auth: false,
    requires_flaresolverr: false,
    pending_credentials: null,
  },
  {
    name: 'dmhy',
    description: 'Taiwanese anime tracker. Cloudflare-gated — routed through FlareSolverr. No account required.',
    search_type: 'dmhy',
    base_url: 'https://share.dmhy.org',
    torznab_url: '',
    api_key: '',
    requires_auth: false,
    requires_flaresolverr: true,
    pending_credentials: null,
  },
  {
    name: 'Uindex',
    description: 'General public tracker (movies, TV, music). Cloudflare-gated — routed through FlareSolverr. No account required.',
    search_type: 'uindex',
    base_url: 'https://uindex.org',
    torznab_url: '',
    api_key: '',
    requires_auth: false,
    requires_flaresolverr: true,
    pending_credentials: null,
  },
]

// Indexers that require an account/API key — surfaced as "pending" in the admin UI.
export const PENDING_INDEXER_CATALOG: IndexerDefinition[] = [
  {
    name: 'IPTorrents',
    description: 'Large private tracker. Requires account + passkey.',
    search_type: 'torznab',
    base_url: 'https://iptorrents.com',
    torznab_url: '',
    api_key: '',
    requires_auth: true,
    requires_flaresolverr: false,
    pending_credentials: { torznab_url: 'Torznab URL (from Prowlarr/Jackett)', api_key: 'API Key' },
  },
  {
    name: 'TorrentLeech',
    description: 'UK-based private tracker. Requires account.',
    search_type: 'torznab',
    base_url: 'https://torrentleech.org',
    torznab_url: '',
    api_key: '',
    requires_auth: true,
    requires_flaresolverr: false,
    pending_credentials: { torznab_url: 'Torznab URL (from Prowlarr/Jackett)', api_key: 'API Key' },
  },
]
